# Example solver resource; override as you see fit.
apiVersion: org.optaplanner.solver/v1
kind: Solver
metadata:
  name: school-timetabling
spec:
  kafkaCluster: my-cluster
  kafkaBootstrapServers: my-cluster-kafka-bootstrap.openshift-operators.svc.cluster.local:9092
  solverImage: quay.io/rsynek/school-timetabling:latest
  replicas: 1