version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: '03:00'
  open-pull-requests-limit: 10
  target-branch: "main"
  commit-message:
    prefix: "[bot]"
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: '03:00'
  open-pull-requests-limit: 0
  target-branch: "7.x"
  commit-message:
    prefix: "[bot][7.x]"
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 0
  target-branch: "7.67.x"
  commit-message:
    prefix: "[bot][7.67.x]"
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: '05:00'
  open-pull-requests-limit: 0
  target-branch: "8.13.x"
  commit-message:
    prefix: "[bot][8.13.x]"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
