language: java
git: # required for auto-assignment of issues in SonarCloud
  depth: false
sudo: false
install: true

jdk:
- oraclejdk8
script:
- mvn --quiet clean install -Prun-code-coverage
- ./travis-sonarcloud.sh
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
