
version: "2.1"

dependencies: ./project-dependencies.yaml

default:
  build-command:
    after:
      upstream: rm -rf ./*

build:
  - project: kiegroup/quarkus
    build-command:
      upstream: mvn -e clean install -fae -Pjava.net.preferIPv4Stack=true -Pquickly -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3

  - project: kiegroup/kogito-runtimes
    build-command:
      upstream: mvn -e clean install -DskipTests -DskipITs=true -fae -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3

  - project: kiegroup/optaplanner
    build-command:
      upstream: mvn -e clean install -Pversion.io.quarkus=999-SNAPSHOT -Pnative -Pquarkus.native.container-build=true -Pquarkus.native.container-runtime=docker -Pquarkus.profile=native -fae -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
      current: |
        mvn -e clean install -Pversion.io.quarkus=999-SNAPSHOT -Pnative,run-code-coverage -Pquarkus.native.container-build=true -Pquarkus.native.container-runtime=docker -Pquarkus.profile=native -fae -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
        mvn -e -nsu validate -Psonar.projectKey=org.optaplanner:optaplanner -Psonarcloud-analysis -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3

  - project: kiegroup/optaplanner-quickstarts
    build-command:
      current: mvn -e clean install -Pversion.io.quarkus=999-SNAPSHOT -Pnative -fae -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3

  - project: kiegroup/quarkus
    build-command:
      upstream: mvn -e clean install -fae -Pjava.net.preferIPv4Stack=true -Pquickly -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
