package org.drools.solver.examples.itc2007.examination.solver;
    dialect "java"

import org.drools.solver.core.score.calculator.HardAndSoftConstraintScoreCalculator;
import org.drools.solver.core.score.constraint.IntConstraintOccurrence;
import org.drools.solver.core.score.constraint.ConstraintType;

import org.drools.solver.examples.pas.domain.AdmissionPart;
import org.drools.solver.examples.pas.domain.Bed;
import org.drools.solver.examples.pas.domain.BedDesignation;
import org.drools.solver.examples.pas.domain.Department;
import org.drools.solver.examples.pas.domain.DepartmentSpecialism;
import org.drools.solver.examples.pas.domain.Equipment;
import org.drools.solver.examples.pas.domain.Gender;
import org.drools.solver.examples.pas.domain.GenderLimitation;
import org.drools.solver.examples.pas.domain.Night;
import org.drools.solver.examples.pas.domain.Patient;
import org.drools.solver.examples.pas.domain.PatientAdmissionSchedule;
import org.drools.solver.examples.pas.domain.PreferredPatientEquipment;
import org.drools.solver.examples.pas.domain.RequiredPatientEquipment;
import org.drools.solver.examples.pas.domain.Room;
import org.drools.solver.examples.pas.domain.RoomEquipment;
import org.drools.solver.examples.pas.domain.RoomSpecialism;
import org.drools.solver.examples.pas.domain.Specialism;
import org.drools.solver.examples.pas.domain.solver.AdmissionPartConflict;
import org.drools.solver.examples.pas.domain.solver.AdmissionPartSpecialismMissingInRoom;

// @author Geoffrey De Smet

// Two patients in the same bed for a number of nights.
rule "sameBedInSameNight"
    when
        $admissionPartConflict : AdmissionPartConflict($leftAdmissionPart : leftAdmissionPart,
                $rightAdmissionPart : rightAdmissionPart);
        $leftBedDesignation : BedDesignation(admissionPart == $leftAdmissionPart, $bed : bed);
        $rightBedDesignation : BedDesignation(admissionPart == $rightAdmissionPart, bed == $bed);
    then
        insertLogical(new IntConstraintOccurrence("sameBedInSameNight",
                ConstraintType.NEGATIVE_HARD, 1000 * $admissionPartConflict.getNightSize(),
                $leftBedDesignation, $rightBedDesignation));
end
