[[introductionToRepeatedPlanning]]
= Introduction to Repeated Planning

The problem facts used to create a solution may change before or during the execution of that solution. Delaying planning in order to lower the risk of problem facts changing is not ideal, as an incomplete plan is preferable to no plan.

The following examples demonstrate situations where planning solutions need to be altered due to unpredictable changes:

* _Unforeseen fact changes_ 

** An employee assigned to a shift calls in sick. 
** An aeroplane scheduled to take off has a technical delay.
** One of the machines or vehicles break down.
+ 
Unforeseen fact changes benefit from using **backup planning**.

* _Cannot assign all entities immediately_
+
Leave some unassigned. For example:
+
** There are 10 shifts at the same time to assign but only nine employees to handle shifts. 
+
For this type of planning, use **overconstrained planning**.

* _Unknown long term future facts_
+
For example:

** Hospital admissions for the next two weeks are reliable, but those for week three and four are less reliable, and for week five and beyond are not worth planning yet. 
+
This problem benefits from **continuous planning**.

* _Constantly changing problem facts_
+
Use **real-time planning**.

More CPU time results in a better planning solution.

Planner allows you to start planning earlier, despite unforeseen changes, as the optimization algorithms support planning a solution that has already been partially planned. This is known as repeated planning.

