name: Generate status page data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  generate-status-page-data:
    if: github.repository == 'apache/incubator-kie-optaplanner'
    concurrency:
      group: generate-status-page-data
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: true
    runs-on: ubuntu-latest
    name: Generate status page data
    steps:
      - name: Generate status page data
        uses: kiegroup/chain-status/.ci/actions/generate-data@main
        with:
          definition-file: https://raw.githubusercontent.com/apache/incubator-kie-optaplanner/main/.ci/builchain-config.yaml
          title: Pull Request Status
          subtitle: OptaPlanner organization repositories CI Status
          base-branch-filter: main,8\.*
          project-filter: apache/incubator-kie-opta.*$
          created-by: GitHub Action
          created-url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          github-token: "${{ secrets.GITHUB_TOKEN }}"

