on:
  # pull_request_target:
  pull_request: # TODO to set back after testing
    branches:
      - main
      - 8.*

jobs:
  label_pr:
    name: Set correct label to PR
    runs-on: ubuntu-latest
    steps:
      - name: Check if organization member belongs
        id: is_organization_member
        uses: radtriste/is-organization-member@debug_gha
        with:
          organization: kiegroup
          username: ${{ github.event.pull_request.user.login }}
          token: ${{ secrets.KIE_CI_READ_ORG_TOKEN }}
      - name: Debug that user belongs to it
        run: |
          echo "User belongs to kiegroup = ${{ steps.is_organization_member.outputs.result }}"
      
      - name: Check if organization member does not belong
        id: is_organization_member_not_belong
        uses: radtriste/is-organization-member@debug_gha
        with:
          organization: kiegroup
          username: anyuser
          token: ${{ secrets.KIE_CI_READ_ORG_TOKEN }}
      - name: Debug that user NOT belongs to it
        run: |
          echo "User belongs to  = ${{ steps.is_organization_member_not_belong.outputs.result }}"