# Runs the SonarCloud analysis of the optaplanner main branch after a PR is merged.
name: OptaPlanner 9

on:
  pull_request:
    types: [ opened, synchronize, reopened, labeled ]
    branches:
      - main
    paths-ignore:
      - 'LICENSE*'
      - '.gitignore'
      - '**.md'
      - '**.adoc'
      - '*.txt'
      - '.ci/**'

defaults:
  run:
    shell: bash

jobs:
  optaplanner-9:
    name: ${{ matrix.os }} - Java ${{ matrix.java-version }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ 17 ]
        maven-version: [ '3.8.7' ]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Java and Maven Setup
        uses: kiegroup/kie-ci/.ci/actions/maven@main
        with:
          java-version: ${{ matrix.java-version }}
          maven-version: ${{ matrix.maven-version }}
          cache-key-prefix: ${{ runner.os }}-${{ matrix.java-version }}-maven${{ matrix.maven-version }}

      - name: Migrate to 9
        run: ./build/8-to-9-migration/migrate.sh --no-version-upgrade --no-commit
      - name: Build with Maven
        run: mvn -B --fail-at-end clean install -Dfull -Dformatter.skip
